import json
import re
from dataclasses import dataclass
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .config import KeywordSyncConfig
from .orchestrator import SyncResult

PR_NUMBER_RE = re.compile(r"\(#(\d+)\)")
TARGET_KEY_RE = re.compile(r"[^A-Za-z0-9]+")


@dataclass(frozen=True)
class PullRequestInfo:
    number: str
    title: str
    url: str
    author: str | None


def write_metadata_files(
        *,
        result: SyncResult,
        config: KeywordSyncConfig,
        output_dir: Path,
        github_token: str | None = None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    outputs_path = output_dir / "outputs.env"
    output_lines = []
    changed_plans = changed_commit_by_target(result)

    for target_name in target_names(result, config):
        plan = changed_plans.get(target_name)
        target_key = output_key(target_name)
        body_path = output_dir / f"{target_key}-pr-body.md"
        comment_path = output_dir / f"{target_key}-pr-comment.md"

        pr_infos = []
        if plan is not None:
            pr_infos = [
                fetch_pr_info(config.tidb_repo, number, github_token)
                for number in extract_pr_numbers_from_message(plan.commit.message)
            ]
        cc_authors = sorted(
            {info.author for info in pr_infos if info.author},
            key=str.casefold,
        )

        body_path.write_text(
            render_pr_body(plan, config, pr_infos),
            encoding="utf-8",
        )
        comment_path.write_text(
            render_cc_comment(cc_authors),
            encoding="utf-8",
        )
        output_lines.extend(
            [
                f"{target_key}_body_path={body_path}",
                f"{target_key}_comment_path={comment_path}",
                f"{target_key}_cc_list={' '.join('@' + author for author in cc_authors)}",
                f"{target_key}_source_commit={plan.commit.sha[:12] if plan else 'none'}",
            ]
        )

    outputs_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")


def extract_pr_numbers(result: SyncResult) -> list[str]:
    numbers = []
    for plan in result.commit_plans:
        for number in extract_pr_numbers_from_message(plan.commit.message):
            if number not in numbers:
                numbers.append(number)
    return numbers


def extract_pr_numbers_from_message(message: str) -> list[str]:
    numbers = []
    for number in PR_NUMBER_RE.findall(message):
        if number not in numbers:
            numbers.append(number)
    return numbers


def changed_commit_by_target(result: SyncResult):
    changed = {}
    for plan in result.commit_plans:
        for target_plan in plan.target_plans:
            if target_plan.changed:
                changed[target_plan.target.name] = plan
    return changed


def target_names(result: SyncResult, config: KeywordSyncConfig) -> list[str]:
    names = []
    for plan in result.commit_plans:
        for target_plan in plan.target_plans:
            if target_plan.target.name not in names:
                names.append(target_plan.target.name)
    if names:
        return names

    for branch in config.branches:
        for target in branch.targets:
            if target.name not in names:
                names.append(target.name)
    return names


def output_key(target_name: str) -> str:
    return TARGET_KEY_RE.sub("_", target_name).strip("_").lower()


def render_pr_body(
        plan,
        config: KeywordSyncConfig,
        pr_infos: list[PullRequestInfo],
) -> str:
    lines = [
        "Automated keyword documentation sync generated from TiDB parser changes.",
        "",
        f"Parser source: `{config.parser_path}`",
        "",
        "## Source TiDB commit",
        "",
    ]

    if plan is None:
        lines.append("- No docs keyword changes were detected for this target.")
    else:
        sha = plan.commit.sha
        lines.append(
            f"- [`{sha[:12]}`](https://github.com/{config.tidb_repo}/commit/{sha}): "
            f"{plan.commit.message}{format_pr_infos(pr_infos)}"
        )

    lines.extend(
        [
            "",
            "Do not commit manual edits to this branch. "
            "It is regenerated by keyword sync.",
            "",
        ]
    )
    return "\n".join(lines)


def format_pr_infos(pr_infos: list[PullRequestInfo]) -> str:
    if not pr_infos:
        return ""
    formatted = []
    for info in pr_infos:
        author = f" @{info.author}" if info.author else ""
        formatted.append(f"[#{info.number}]({info.url}){author}")
    return ", " + ", ".join(formatted)


def render_cc_comment(authors: list[str]) -> str:
    if not authors:
        return ""
    return "/cc " + " ".join(f"@{author}" for author in authors) + "\n"


def fetch_pr_info(
        repo: str,
        number: str,
        token: str | None,
) -> PullRequestInfo:
    url = f"https://api.github.com/repos/{repo}/pulls/{number}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "keyword-sync",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = Request(url, headers=headers)
    try:
        with urlopen(request, timeout=30) as response:
            data = json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, TimeoutError) as err:
        raise RuntimeError(f"Failed to fetch TiDB PR #{number}: {err}") from err

    user = data.get("user") or {}
    return PullRequestInfo(
        number=str(data["number"]),
        title=data["title"],
        url=data["html_url"],
        author=user.get("login"),
    )
